on:
  workflow_call:
    inputs:
      dir-to-release-name:
        required: false
        type: string
        default: ""

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed directories
        id: changed-dir-names
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          json: true
          files: "**/manifests/**"
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Set matrix
        id: set-matrix
        run: |
          dirs=$(echo "${{ steps.changed-dir-names.outputs.all_changed_files }}" | jq -c '[.[] | select((split("/") | .[-1] | split(".") | .[0]) | IN("prod", "dev", "stg"))]')
          echo "Changed directories: ${dirs}"

          if [ -z "${dirs}" ]; then
            echo "No changed directories found."
          else
            matrix=$(echo "${dirs}" | jq -c '[.[] | {path: ., env: (split("/") | .[-1]) | split(".") | .[0], dir: .[:rindex("/")]}]' | jq -c '{include: .}')
          fi
          echo "matrix=${matrix}" | tee -a "$GITHUB_OUTPUT"

  test:
    needs: [get-changed-files]
    if: ${{ fromJSON(needs.get-changed-files.outputs.matrix).include }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: set release name
        run: |
          if [ -z "${{ inputs.dir-to-release-name }}" ]; then
            echo "dir-to-release-name is not set"
          else
            if [ -z "${{ fromJSON(inputs.dir-to-release-name)[matrix.dir] }}" ]; then
              echo "release name is not set"
            else
              echo "RELEASE_NAME=${{ fromJSON(inputs.dir-to-release-name)[matrix.dir] }}" >> $GITHUB_ENV
            fi
          fi
      - name: show release name
        if: env.RELEASE_NAME != ''
        run: |
          echo "RELEASE_NAME=${{ env.RELEASE_NAME }}"
      - name: show dummy name
        if: env.RELEASE_NAME == ''
        run: |
          echo "RELEASE_NAME=dummy"
